
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: breath_dev

test:
  <<: *default
  database: breath_test

production:
  <<: *default
  database: breath_prod
